package com.micro.client.publish.common;

public enum PUBLISHTYPE {
	PERFORMANCEMETRIC,
	CONTAINERINFO, 
	DELETEDCONTAINERS, 
	COMMANDS, 
	FILE_DIFF, 
	PROCESSES, 
	NETWORK_CREATE, 
	NETWORK_CONNECT, 
	NETWORK_DESTROY,
	NETWORK_DISCONNECT,
	NETWORK_REMOVE,
	CONTAINERLIST, NETWORK_LIST;
}
